from sdl2.rect import SDL_Rect
from dataclasses import dataclass
import math

from compygui.datatypes.vector2 import Vector2, IVector2


@dataclass
class Rect2:
    """A 2D rectangle.

    x: Position on the X axis.
    y: Position on the Y axis.
    w: Size on the X axis (width).
    h: Size on the Y axis (height).
    """

    def __init__(self, x: float, y: float, w: float, h: float) -> None:
        super().__init__()
        self.x: float = x
        self.y: float = y
        self.w: float = w
        self.h: float = h

    @staticmethod
    def from_vectors(topleft: Vector2 | IVector2, size: Vector2 | IVector2) -> Rect2:
        """Creates a Rect2() from two Vector2()s/IVector2()s

        topleft: The Vector2()/IVector2() that provides the X and Y components
        size: The Vector2()/IVector2() that provides the W and H components
        """
        return Rect2(topleft.x, topleft.y, size.x, size.y)

    @staticmethod
    def ZERO() -> Rect2:
        """Equivalent to Rect2(0, 0, 0, 0)"""
        return Rect2(0, 0, 0, 0)

    @staticmethod
    def ONE() -> Rect2:
        """Equivalent to Rect2(0, 0, 0, 0)"""
        return Rect2(0, 0, 0, 0)

    def center(self) -> Vector2:
        """Returns the position of the center of the Rect2() as a Vector2()"""
        return Vector2(self.x + (self.w / 2.0), self.y + (self.h / 2.0))

    def topleft(self) -> Vector2:
        """Equivalent to Vector2(self.x, self.y)"""
        return Vector2(self.x, self.y)

    def size(self) -> Vector2:
        """Equivalent to Vector2(self.w, self.h)"""
        return Vector2(self.w, self.h)

    def rounded(self) -> IRect2:
        """Returns an IRect2() generated by rounding this Rect2()"""
        return IRect2(
            int(round(self.x)),
            int(round(self.y)),
            int(round(self.w)),
            int(round(self.h)),
        )

    def ceiled(self) -> IRect2:
        """Returns an IRect2() generated by ceiling (rounding up) this Rect2()"""
        return IRect2(
            int(math.ceil(self.x)),
            int(math.ceil(self.y)),
            int(math.ceil(self.w)),
            int(math.ceil(self.h)),
        )

    def floored(self) -> IRect2:
        """Returns an IRect2() generated by ceiling (rounding down) this Rect2()"""
        return IRect2(
            int(math.floor(self.x)),
            int(math.floor(self.y)),
            int(math.floor(self.w)),
            int(math.floor(self.h)),
        )


@dataclass
class IRect2:
    """An integer 2D rectangle."""

    def __init__(self, x: int, y: int, w: int, h: int) -> None:
        super().__init__()
        self.x: int = x
        self.y: int = y
        self.w: int = w
        self.h: int = h

    @staticmethod
    def from_vectors(topleft: IVector2, size: IVector2) -> IRect2:
        """Creates an IRect2() from two IVector2()s

        topleft: The IVector2() that provides the X and Y components
        size: The IVector2() that provides the W and H components
        """
        return IRect2(topleft.x, topleft.y, size.x, size.y)

    @staticmethod
    def ZERO() -> IRect2:
        """Equivalent to IRect2(0, 0, 0, 0)"""
        return IRect2(0, 0, 0, 0)

    @staticmethod
    def ONE() -> IRect2:
        """Equivalent to IRect2(1, 1, 1, 1)"""
        return IRect2(1, 1, 1, 1)

    def center(self) -> IVector2:
        """Returns the position of the center of the IRect2() as a IVector2()"""
        return IVector2(self.x + (self.w // 2), self.y + (self.h // 2))

    def topleft(self) -> IVector2:
        """Equivalent to IVector2(self.x, self.y)"""
        return IVector2(self.x, self.y)

    def size(self) -> IVector2:
        """Equivalent to IVector2(self.w, self.h)"""
        return IVector2(self.w, self.h)

    def floaty(self) -> Rect2:
        """Returns an IRect2() generated by rounding this Rect2()"""
        return Rect2(self.x, self.y, self.w, self.h)

    def as_sdl_rect(self) -> SDL_Rect:
        """Returns an SDL_Rect structure with the values of this IRect2()"""
        return SDL_Rect(x=self.x, y=self.y, w=self.w, h=self.h)
