from typing import Any
from dataclasses import dataclass
import math


@dataclass
class IVector2:
    """An integer 2D vector

    X: The X axis
    Y: The Y axis
    """

    def __init__(self, x: int, y: int) -> None:
        super().__init__()
        self.x: int = x
        self.y: int = y

    @staticmethod
    def ZERO() -> IVector2:
        """Equivalent to IVector2(0, 0)."""
        return IVector2(0, 0)

    @staticmethod
    def ONE() -> IVector2:
        """Equivalent to IVector2(1, 1)."""
        return IVector2(1, 1)

    @staticmethod
    def UP() -> IVector2:
        """Equivalent to IVector2(0, -1)."""
        return IVector2(0, -1)

    @staticmethod
    def DOWN() -> IVector2:
        """Equivalent to IVector2(0, 1)."""
        return IVector2(0, 1)

    @staticmethod
    def LEFT() -> IVector2:
        """Equivalent to IVector2(-1, 0)."""
        return IVector2(-1, 0)

    @staticmethod
    def RIGHT() -> IVector2:
        """Equivalent to IVector2(1, 0)."""
        return IVector2(1, 0)

    def normalized(self) -> Vector2:
        """Returns a normalized (length == 1) version of this IVector2() as a Vector2()"""
        magnitude: float = self.magnitude()
        return Vector2(float(self.x) / magnitude, float(self.y) / magnitude)

    def magnitude(self) -> float:
        """Returns the magnitude (length/module) of this IVector2()"""
        return math.sqrt((self.x**2) + (self.y**2))

    def floaty(self) -> Vector2:
        """Returns a Vector2() generated with the values of this IVector2()"""
        return Vector2(self.x, self.y)


@dataclass
class Vector2:
    """A 2D vector

    x: The X axis
    y: The Y axis
    """

    def __init__(self, x: float, y: float) -> None:
        super().__init__()
        self.x: float = x
        self.y: float = y

    def magnitude(self) -> float:
        """Returns the magnitude (length/module) of this Vector2()"""
        return math.sqrt((self.x**2) + (self.y**2))

    @staticmethod
    def ZERO() -> Vector2:
        """Equivalent to Vector2(0, 0)."""
        return Vector2(0, 0)

    @staticmethod
    def ONE() -> Vector2:
        """Equivalent to Vector2(1, 1)."""
        return Vector2(1, 1)

    @staticmethod
    def UP() -> Vector2:
        """Equivalent to Vector2(0, -1)."""
        return Vector2(0, -1)

    @staticmethod
    def DOWN() -> Vector2:
        """Equivalent to Vector2(0, 1)."""
        return Vector2(0, 1)

    @staticmethod
    def LEFT() -> Vector2:
        """Equivalent to Vector2(-1, 0)."""
        return Vector2(-1, 0)

    @staticmethod
    def RIGHT() -> Vector2:
        """Equivalent to Vector2(1, 0)."""
        return Vector2(1, 0)

    def rounded(self) -> IVector2:
        """Returns an IVector2() generated by rounding this Vector2()"""
        return IVector2(int(round(self.x)), int(round(self.y)))

    def ceiled(self) -> IVector2:
        """Returns an IVector2() generated by ceiling (rounding up) this Vector2()"""
        return IVector2(int(math.ceil(self.x)), int(math.ceil(self.y)))

    def floored(self) -> IVector2:
        """Returns an IVector2() generated by flooring (rounding down) this Vector2()"""
        return IVector2(int(math.floor(self.x)), int(math.floor(self.y)))

    def normalized(self) -> Vector2:
        """Returns a normalized (length == 1) version of this Vector2()"""
        magnitude: float = self.magnitude()
        return Vector2(self.x / magnitude, self.y / magnitude)
