"""
ComPyGUI - A competent Python GUI library
  Copyright (C) 2026  FluffyKn1ght

Please see the NOTICE file or compygui.compygui.ComPyGuiApp.NOTICE
for important license information.
https://github.com/FluffyKn1ght/compygui
"""

import math

from dataclasses import dataclass
from typing import Any

from sdl2.rect import SDL_Rect


@dataclass
class IVector2:
    """An integer 2D vector."""

    def __init__(self, x: int, y: int) -> None:
        super().__init__()
        self.x: int = x
        self.y: int = y

    def __or__(self, value: Any) -> IVector2:
        if type(value) is IVector2:
            return IVector2(
                self.x if self.x != 0 else value.x, self.y if self.y != 0 else value.y
            )
        else:
            raise ValueError(
                f"Can't {'"|"'} an IVector2 and {type(value).__name__} together "
            )

    def floaty(self) -> Vector2:
        """Returns a Vector2() generated with the values of this IVector2()"""
        return Vector2(self.x, self.y)

    @staticmethod
    def ZERO() -> IVector2:
        """Equivalent to IVector2(0, 0)."""
        return IVector2(0, 0)

    @staticmethod
    def ONE() -> IVector2:
        """Equivalent to IVector2(1, 1)."""
        return IVector2(1, 1)

    @staticmethod
    def UP() -> IVector2:
        """Equivalent to IVector2(0, -1)."""
        return IVector2(0, -1)

    @staticmethod
    def DOWN() -> IVector2:
        """Equivalent to IVector2(0, 1)."""
        return IVector2(0, 1)

    @staticmethod
    def LEFT() -> IVector2:
        """Equivalent to IVector2(-1, 0)."""
        return IVector2(-1, 0)

    @staticmethod
    def RIGHT() -> IVector2:
        """Equivalent to IVector2(1, 0)."""
        return IVector2(1, 0)


@dataclass
class Vector2:
    """A 2D vector.

    x: The X axis.
    y: The Y axis.
    """

    def __init__(self, x: float, y: float) -> None:
        super().__init__()
        self.x: float = x
        self.y: float = y

    def __or__(self, value: Any) -> Vector2:
        if type(value) is Vector2:
            return Vector2(
                self.x if self.x != 0 else value.x, self.y if self.y != 0 else value.y
            )
        else:
            raise ValueError(
                f"Can't {'"|"'} a Vector2 and {type(value).__name__} together "
            )

    @staticmethod
    def ZERO() -> Vector2:
        """Equivalent to Vector2(0, 0)."""
        return Vector2(0, 0)

    @staticmethod
    def ONE() -> Vector2:
        """Equivalent to Vector2(1, 1)."""
        return Vector2(1, 1)

    @staticmethod
    def UP() -> Vector2:
        """Equivalent to Vector2(0, -1)."""
        return Vector2(0, -1)

    @staticmethod
    def DOWN() -> Vector2:
        """Equivalent to Vector2(0, 1)."""
        return Vector2(0, 1)

    @staticmethod
    def LEFT() -> Vector2:
        """Equivalent to Vector2(-1, 0)."""
        return Vector2(-1, 0)

    @staticmethod
    def RIGHT() -> Vector2:
        """Equivalent to Vector2(1, 0)."""
        return Vector2(1, 0)

    def rounded(self) -> IVector2:
        """Returns an IVector2() generated by rounding this Vector2()"""
        return IVector2(int(round(self.x)), int(round(self.y)))

    def ceiled(self) -> IVector2:
        """Returns an IVector2() generated by ceiling (rounding up) this Vector2()"""
        return IVector2(int(math.ceil(self.x)), int(math.ceil(self.y)))

    def floored(self) -> IVector2:
        """Returns an IVector2() generated by flooring (rounding down) this Vector2()"""
        return IVector2(int(math.floor(self.x)), int(math.floor(self.y)))

    def normalized(self) -> Vector2:
        """Returns a normalized (length == 1) version of this Vector2()"""
        return Vector2(self.x / self.x, self.y / self.y)


@dataclass
class Rect2:
    """A 2D rectangle.

    x: Position on the X axis.
    y: Position on the Y axis.
    w: Size on the X axis (width).
    h: Size on the Y axis (height).
    """

    def __init__(self, x: float, y: float, w: float, h: float) -> None:
        super().__init__()
        self.x: float = x
        self.y: float = y
        self.w: float = w
        self.h: float = h

    @staticmethod
    def from_vectors(topleft: Vector2 | IVector2, size: Vector2 | IVector2) -> Rect2:
        """Creates a Rect2() from two Vector2()s/IVector2()s

        topleft: The Vector2()/IVector2() that provides the X and Y components
        size: The Vector2()/IVector2() that provides the W and H components
        """
        return Rect2(topleft.x, topleft.y, size.x, size.y)

    @staticmethod
    def ZERO() -> Rect2:
        """Equivalent to Rect2(0, 0, 0, 0)"""
        return Rect2(0, 0, 0, 0)

    @staticmethod
    def ONE() -> Rect2:
        """Equivalent to Rect2(0, 0, 0, 0)"""
        return Rect2(0, 0, 0, 0)

    def center(self) -> Vector2:
        """Returns the position of the center of the Rect2() as a Vector2()"""
        return Vector2(self.x + (self.w / 2.0), self.y + (self.h / 2.0))

    def rounded(self) -> IRect2:
        """Returns an IRect2() generated by rounding this Rect2()"""
        return IRect2(
            int(round(self.x)),
            int(round(self.y)),
            int(round(self.w)),
            int(round(self.h)),
        )

    def ceiled(self) -> IRect2:
        """Returns an IRect2() generated by ceiling (rounding up) this Rect2()"""
        return IRect2(
            int(math.ceil(self.x)),
            int(math.ceil(self.y)),
            int(math.ceil(self.w)),
            int(math.ceil(self.h)),
        )

    def floored(self) -> IRect2:
        """Returns an IRect2() generated by ceiling (rounding down) this Rect2()"""
        return IRect2(
            int(math.floor(self.x)),
            int(math.floor(self.y)),
            int(math.floor(self.w)),
            int(math.floor(self.h)),
        )


@dataclass
class IRect2:
    """An integer 2D rectangle."""

    def __init__(self, x: int, y: int, w: int, h: int) -> None:
        super().__init__()
        self.x: int = x
        self.y: int = y
        self.w: int = w
        self.h: int = h

    @staticmethod
    def from_vectors(topleft: IVector2, size: IVector2) -> IRect2:
        """Creates an IRect2() from two IVector2()s

        topleft: The IVector2() that provides the X and Y components
        size: The IVector2() that provides the W and H components
        """
        return IRect2(topleft.x, topleft.y, size.x, size.y)

    @staticmethod
    def ZERO() -> IRect2:
        """Equivalent to IRect2(0, 0, 0, 0)"""
        return IRect2(0, 0, 0, 0)

    @staticmethod
    def ONE() -> IRect2:
        """Equivalent to IRect2(1, 1, 1, 1)"""
        return IRect2(1, 1, 1, 1)

    def center(self) -> IVector2:
        """Returns the position of the center of the IRect2() as a IVector2()"""
        return IVector2(self.x + (self.w // 2), self.y + (self.h // 2))

    def floaty(self) -> Rect2:
        """Returns an IRect2() generated by rounding this Rect2()"""
        return Rect2(self.x, self.y, self.w, self.h)

    def as_sdl_rect(self) -> SDL_Rect:
        """Returns an SDL_Rect structure with the values of this IRect2()"""
        return SDL_Rect(x=self.x, y=self.y, w=self.w, h=self.h)
